name: 'aws-nuke'
on: 
  push:
  workflow_dispatch:
  schedule: 
    - cron: '0 3 * * *'

jobs:
  nuke: 
    name: 'aws-nuke'
    runs-on: ubuntu-20.04
    steps:
      - name: 'checkout'
        uses: actions/checkout@v2.3.4

      - name: 'login to aws'
        id: login-aws
        uses: aws-action/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: 'setup nuke-tool'
        run: |
          wget https://github.com/rebuy-de/aws-nuke/releases/download/v2.16.0/aws-nuke-v2.16.0-linux-amd64.tar.gz
          tar -xvzf aws-nuke-v2.16.0-linux-amd64.tar.gz
          chmod u+x aws-nuke-v2.16.0-linux-amd64
          mv aws-nuke-v2.16.0-linux-amd64 /usr/local/bin/aws-nuke          
          aws-nuke -h
        
      - name: 'nuke-run'
        run: |
          cd _nuke && chmod +x run.sh && ./run.sh 
